"""add parent col to events

Revision ID: 324c3d121c01
Revises: 4610d7ecc554
Create Date: 2026-03-17 11:52:50.617312

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "324c3d121c01"
down_revision: str | Sequence[str] | None = "4610d7ecc554"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("parent", sa.TEXT(), nullable=False))
    op.create_index(op.f("ix_events_parent"), "events", ["parent"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_events_parent"), table_name="events")
    op.drop_column("events", "parent")
    # ### end Alembic commands ###
