"""add parent col to events

Revision ID: 430d611b6667
Revises: db590b6ee82b
Create Date: 2026-03-17 11:47:09.855514

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "430d611b6667"
down_revision: str | Sequence[str] | None = "db590b6ee82b"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("parent", sa.Text(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "parent")
    # ### end Alembic commands ###
