"""add parent col to events

Revision ID: 4610d7ecc554
Revises: 430d611b6667
Create Date: 2026-03-17 11:51:25.974176

"""

from collections.abc import Sequence

import sqlalchemy as sa

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4610d7ecc554"
down_revision: str | Sequence[str] | None = "430d611b6667"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("events", "parent")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("events", sa.Column("parent", sa.TEXT(), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
